// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertToPdf(arg1:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetNotes():Promise<Array<main.Note>>;

export function Greet(arg1:string):Promise<string>;

export function SaveNote(arg1:main.Note):Promise<void>;

export function SearchNotes(arg1:string):Promise<Array<main.Note>>;
