// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToPdf(arg1) {
  return window['go']['main']['App']['ConvertToPdf'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function SearchNotes(arg1) {
  return window['go']['main']['App']['SearchNotes'](arg1);
}
